### ISSUE TITLE
Support for AWS-SDK v3

### ISSUE THREAD

**Issue by mark-muhammad** [kyh/multer-s3#25]
Hello @kyh,
Do you plan to update this lib to support AWS-SDK v3? I see there is already a pull request for this (#23) but still not merged. It will be great to have this change up and running since AWS keeps telling us to update.

Thanks for writing this library.

**Comment by kyh** [comment]
Sorry, unfortunately I haven't been actively working on this codebase anymore and I haven't had the need for it. Feel free to fork it to keep it up to day. I'll be marking the repository as archived
